### PR TITLE
B#236 fix updater test

### LINKED ISSUE #236: [sr_robot_lib] motor_update test concept
We face the same issue as #189 again. 
I looked at the timing again, and what happens is that the CAN_NUM message are in time (within the tolerance) but too soon
so that the function
```
fabs(time_spent.toSec() - (static_cast<double>(static_cast<int>(time_spent.toSec())))) < tolerancy

```
misses it.

when I add a print of the timing at each loop + a new test in addition to the existing one, one sees the problem 

```
(...)
[ INFO] [1606495014.653630553]: time spent from start: 0.994063919 time integer:0 diff:0.994064
[ INFO] [1606495014.654630402]: time spent from start: 0.995063778 time integer:0 diff:0.995064
[ INFO] [1606495014.655630649]: time spent from start: 0.996063957 time integer:0 diff:0.996064
[ INFO] [1606495014.656702165]: time spent from start: 0.997137145 time integer:0 diff:0.997137
[ INFO] [1606495014.656726837]: NEW TEST : CAN data received at correct time: 0.997137145 => is within the 0.01 tolerance
[ INFO] [1606495014.657627622]: time spent from start: 0.998061091 time integer:0 diff:0.998061
[ INFO] [1606495014.658630687]: time spent from start: 0.999064212 time integer:0 diff:0.999064
[ INFO] [1606495014.659637700]: time spent from start: 1.000064007 time integer:1 diff:6.4007e-05
[ INFO] [1606495014.659660479]: OLD TEST : NOT a CAN data received at time : 1.000064007 => entered the period of validity of the tolerance but message will not come for more than 1 second now since it arrived before.
[ INFO] [1606495014.660630297]: time spent from start: 1.001063340 time integer:1 diff:0.00106334
[ INFO] [1606495014.660652875]: OLD TEST : NOT a CAN data received at time : 1.001063340
[ INFO] [1606495014.661630211]: time spent from start: 1.002063351 time integer:1 diff:0.00206335
[ INFO] [1606495014.661659629]: OLD TEST : NOT a CAN data received at time : 1.002063351
[ INFO] [1606495014.662630324]: time spent from start: 1.003063428 time integer:1 diff:0.00306343
[ INFO] [1606495014.662652734]: OLD TEST : NOT a CAN data received at time : 1.003063428
[ INFO] [1606495014.663630143]: time spent from start: 1.004063295 time integer:1 diff:0.00406329
[ INFO] [1606495014.663652924]: OLD TEST : NOT a CAN data received at time : 1.004063295
[ INFO] [1606495014.664630224]: time spent from start: 1.005063326 time integer:1 diff:0.00506333
[ INFO] [1606495014.664652760]: OLD TEST : NOT a CAN data received at time : 1.005063326
[ INFO] [1606495014.665630229]: time spent from start: 1.006063336 time integer:1 diff:0.00606334
[ INFO] [1606495014.665652734]: OLD TEST : NOT a CAN data received at time : 1.006063336
[ INFO] [1606495014.666630170]: time spent from start: 1.007063314 time integer:1 diff:0.00706331
[ INFO] [1606495014.666657373]: OLD TEST : NOT a CAN data received at time : 1.007063314
[ INFO] [1606495014.667630230]: time spent from start: 1.008063353 time integer:1 diff:0.00806335
[ INFO] [1606495014.667653348]: OLD TEST : NOT a CAN data received at time : 1.008063353
[ INFO] [1606495014.668630151]: time spent from start: 1.009063296 time integer:1 diff:0.0090633
[ INFO] [1606495014.668652834]: OLD TEST : NOT a CAN data received at time : 1.009063296
[ INFO] [1606495014.669630590]: time spent from start: 1.010063768 time integer:1 diff:0.0100638
[ INFO] [1606495014.670630129]: time spent from start: 1.011063426 time integer:1 diff:0.0110634
[ INFO] [1606495014.671630317]: time spent from start: 1.012063543 time integer:1 diff:0.0120635
[ INFO] [1606495014.672629921]: time spent from start: 1.013063138 time integer:1 diff:0.0130631
```

So I suppose the test must be rewritten, because adding a larger tolerance as done in #223 will not help. I have a PR almost ready please wait

### PR DESCRIPTION
**Pull request by guihomework**
## Proposed changes

Resolves #236 and reverts #223 

## Types of changes

What types of changes does your code introduce?

- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

Put an x in the boxes that apply. You can also fill these out after creating the PR. This is a reminder of what we should look for before merging this code. I have:

- [X] Read and follow the [contributing guidelines](https://github.com/shadow-robot/sr_documentation/blob/master/CONTRIBUTING.md).
- [X] Checked that all tests pass with my changes

### CODE REVIEW

File: sr_robot_lib/test/motor_updater_test.cpp [hunk 1]
```diff
@@ -107,13 +108,17 @@ class MotorUpdaterTest
         }
       }
 
-
-      if (fabs(time_spent.toSec() - (static_cast<double>(static_cast<int>(time_spent.toSec())))) < tolerancy)
+      if (command->from_motor_data_type == MOTOR_DATA_CAN_NUM_RECEIVED)
       {
-        if (command->from_motor_data_type == MOTOR_DATA_CAN_NUM_RECEIVED)
+        can_num_transmitted_counter++;
+           if (fabs(time_spent.toSec() - (can_num_transmitted_counter * test3.when_to_update)) < tolerancy)
```
Comment (beatrizleon) [inline sr_robot_lib/test/motor_updater_test.cpp]:
```suggestion
        if (fabs(time_spent.toSec() - (can_num_transmitted_counter * test3.when_to_update)) < tolerancy)
```

**Review by beatrizleon — CHANGES_REQUESTED** [review]

File: sr_robot_lib/test/motor_updater_test.cpp (hunk 1 above)
Comment (guihomework) [reply sr_robot_lib/test/motor_updater_test.cpp]: interestingly roslint cpplint did not find this offset. Sorry. Fixed

**Review by ghost — APPROVED** [review]

**Review by biofotis — APPROVED** [review]

**Review by beatrizleon — APPROVED** [review]
